default: &default
  adapter: postgresql
  encoding: unicode
  user: davejc
  password: davejc

development:
  <<: *default
  adapter: postgresql
  database: dev_dave2-solidus
  pool: 5
  timeout: 50
  host: localhost
  username: davejc
  password: davejc

test:
  <<: *default
  adapter: postgresql
  database: test_dave2-solidus
  pool: 5
  timeout: 50
  host: localhost
  username: davejc
  password: davejc
  
production:
  <<: *default
  database: prod_dave2-solidus
  username: davejc
  password: davejc